# Generated by Django 4.0.5 on 2022-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hund_mountain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('areatreason', models.TextField(blank=True, null=True)),
                ('areanm', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('etccourse', models.TextField(blank=True, null=True)),
                ('mntheight', models.FloatField(blank=True, null=True)),
                ('mntnm', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('subnm', models.TextField(blank=True, null=True)),
                ('tourisminf', models.TextField(blank=True, null=True)),
                ('transport', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mountain3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lot', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.TextField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('lot', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
