# Generated by Django 4.0.5 on 2022-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hund_mountain', '0002_mountain3_subway_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.TextField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lot', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveWeather',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('rainp', models.IntegerField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('hum', models.IntegerField(blank=True, null=True)),
                ('wspd', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'live_weather',
                'managed': False,
            },
        ),
    ]
